language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

install:
  - cargo install wasm-pack

jobs:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - wasm-pack build --target web --release --out-dir example/pkg && rm example/pkg/.gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: example
  keep_history: true
  on:
    branch: master